import Head from "next/head";
import MealList from "../components/MealList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next-Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MealList />
    </>
  );
}
